import threading
import subprocess
import time

def run_script(script_name):
    subprocess.run(["python", script_name])

if __name__ == "__main__":
    script1_thread = threading.Thread(target=run_script, args=("server.py",))
    script2_thread = threading.Thread(target=run_script, args=("client.py",))
    script3_thread = threading.Thread(target=run_script, args=("roboclient1.py",))
    script4_thread = threading.Thread(target=run_script, args=("roboclient2.py",))
    script5_thread = threading.Thread(target=run_script, args=("roboclient3.py",))
    script6_thread = threading.Thread(target=run_script, args=("roboclient4.py",))
    script7_thread = threading.Thread(target=run_script, args=("roboclient5.py",))
    script8_thread = threading.Thread(target=run_script, args=("roboclient6.py",))
    script9_thread = threading.Thread(target=run_script, args=("roboclient7.py",))
    script10_thread = threading.Thread(target=run_script, args=("roboclient8.py",))
    script11_thread = threading.Thread(target=run_script, args=("roboclient9.py",))
    script12_thread = threading.Thread(target=run_script, args=("roboclient10.py",))
    script13_thread = threading.Thread(target=run_script, args=("roboclient11.py",))
    script14_thread = threading.Thread(target=run_script, args=("roboclient12.py",))
    script15_thread = threading.Thread(target=run_script, args=("roboclient13.py",))
    script16_thread = threading.Thread(target=run_script, args=("roboclient14.py",))
    script17_thread = threading.Thread(target=run_script, args=("roboclient15.py",))
    script18_thread = threading.Thread(target=run_script, args=("roboclient16.py",))
    script19_thread = threading.Thread(target=run_script, args=("roboclient17.py",))
    script20_thread = threading.Thread(target=run_script, args=("roboclient18.py",))
    script21_thread = threading.Thread(target=run_script, args=("roboclient19.py",))

    script1_thread.start()
    time.sleep(0.5)
    script2_thread.start()
    script3_thread.start()
    script4_thread.start()
    script5_thread.start()
    script6_thread.start()
    script7_thread.start()
    script8_thread.start()
    script9_thread.start()
    script10_thread.start()
    script11_thread.start()
    script12_thread.start()
    script13_thread.start()
    script14_thread.start()
    script15_thread.start()
    script16_thread.start()
    script17_thread.start()
    script18_thread.start()
    script19_thread.start()
    script20_thread.start() 
    script21_thread.start()

    script1_thread.join()
    script2_thread.join()
    script3_thread.join()
    script4_thread.join()
    script5_thread.join()
    script6_thread.join()
    script7_thread.join()
    script8_thread.join()
    script9_thread.join()
    script10_thread.join()
    script11_thread.join()
    script12_thread.join()
    script13_thread.join()
    script14_thread.join()
    script15_thread.join()
    script16_thread.join()
    script17_thread.join()
    script18_thread.join()
    script19_thread.join()
    script20_thread.join()
    script21_thread.join()

    print("Scripts have finished executing.")